apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./examples/sample-gitops/clusters/production
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  prune: true
  validation: client