apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: '12.x.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      postgresPassword: "postgres"
      database: "backend"
    primary:
      persistence:
        enabled: true
        size: 8Gi
