apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  path: ./examples/sample-gitops/infrastructure
  sourceRef:
    kind: GitRepository
    name: gitops-repo
  interval: 5m
  prune: true
  wait: true
  timeout: 10m
  retryInterval: 1m
  serviceAccountName: flux-system
