apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  path: ./examples/sample-gitops/clusters/production
  sourceRef:
    kind: GitRepository
    name: gitops-repo
  interval: 1m
  prune: true
  wait: true

  