# GitOps Validator Configuration
# This file configures the validation rules and settings

# Repository path to validate (default: current directory)
path: "."

# Verbose output
verbose: false

# Path to deprecated APIs YAML file (default: data/deprecated-apis.yaml)
yaml-path: ""

# Validation rules configuration
rules:
  # Flux Kustomization validation
  flux-kustomization:
    enabled: true
    severity: "error"
    
  # Kubernetes Kustomization validation  
  kubernetes-kustomization:
    enabled: true
    severity: "error"
    
  # Orphaned resource detection
  orphaned-resources:
    enabled: true
    severity: "warning"
    
  # Deprecated API detection
  deprecated-apis:
    enabled: true
    severity: "warning"
    
# Custom deprecated APIs (additional to built-in list)
custom-deprecated-apis:
  # Example:
  # "mycompany.com/v1alpha1": "Deprecated in v1.0, will be removed in v2.0"

# Chart generation settings
chart:
  enabled: false
  format: "mermaid"  # mermaid, tree, json
  output: ""        # output file path (empty = stdout)
  include-orphaned: true
  include-metadata: true

# Ignore patterns for files/directories
ignore:
  directories:
    - ".git/**"
    - ".github/**"
    - ".gitlab-ci/**"
    - ".circleci/**"
    - ".azure-pipelines/**"
    - "node_modules/**"
    - "vendor/**"
    - "tmp/**"
    - "temp/**"
    - "build/**"
    - "dist/**"
    - "bin/**"
  files:
    - "*.log"
    - "*.tmp"
    - "*.temp"
    - ".DS_Store"
    - "Thumbs.db"
  
# Entry point patterns (files that are considered valid even if not referenced)
entry-points:
  - "**/kustomization.yaml"
  - "**/kustomization.yml"
  - "**/flux-system/**"