apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: test-kustomization
resources:
  - deployment.yaml
patchesStrategicMerge:
  # String format (existing)
  - patch1.yaml
  # File object format (new)
  - path: patch2.yaml
  # Mixed with relative paths
  - ./patches/patch3.yaml
  - path: ./patches/patch4.yaml
