apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: production
spec:
  chart:
    spec:
      chart: backend
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: my-repo
  interval: 5m
  install:
    createNamespace: true