apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: production
spec:
  chart:
    spec:
      chart: postgresql
      version: "12.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m