name: GitOps Validation with Configuration-Based Error Handling

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-gitops:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install GitOps Validator
      run: |
        go install github.com/moon-hex/gitops-validator@latest
        
    - name: Create Configuration File
      run: |
        cat > .gitops-validator.yaml << 'EOF'
        # GitOps Validator Configuration
        gitops-validator:
          path: "."
          verbose: true
          
          # Validation rules
          rules:
            flux-kustomization:
              enabled: true
              severity: "error"
            kubernetes-kustomization:
              enabled: true
              severity: "error"
            orphaned-resources:
              enabled: true
              severity: "warning"
            deprecated-apis:
              enabled: true
              severity: "warning"
          
          # Exit code configuration
          exit-codes:
            fail-on-errors: true      # Fail on errors (exit code 1)
            fail-on-warnings: false  # Don't fail on warnings (exit code 2)
            fail-on-info: false      # Don't fail on info (exit code 3)
          
          # Ignore patterns
          ignore:
            directories:
              - ".git/**"
              - ".github/**"
              - "node_modules/**"
              - "vendor/**"
              - "tmp/**"
              - "temp/**"
              - "build/**"
              - "dist/**"
              - "bin/**"
            files:
              - "*.log"
              - "*.tmp"
              - "*.temp"
              - ".DS_Store"
              - "Thumbs.db"
          
          # Chart generation
          chart:
            enabled: true
            format: "mermaid"
            output: "dependency-chart.md"
            include-orphaned: true
            include-metadata: true
        EOF
        
    - name: Run GitOps Validation
      id: validation
      run: |
        # Run validation with configuration
        gitops-validator --path . --verbose
      continue-on-error: true
      
    - name: Generate Dependency Chart
      if: steps.validation.outcome == 'success'
      run: |
        # Chart generation is configured in the config file
        gitops-validator --path . --chart mermaid --chart-output dependency-chart.md --verbose
        
    - name: Comment PR with Results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          let comment = `## 🔍 GitOps Validation Results\n\n`;
          
          if ('${{ steps.validation.outcome }}' === 'success') {
            comment += `✅ **Validation Passed**: No errors found in GitOps configuration\n\n`;
            
            // Add chart if available
            try {
              const chart = fs.readFileSync('dependency-chart.md', 'utf8');
              comment += `### 📊 Dependency Chart\n\n`;
              comment += `\`\`\`mermaid\n${chart}\n\`\`\`\n\n`;
            } catch (error) {
              comment += `📊 Dependency chart generation skipped\n\n`;
            }
          } else {
            comment += `❌ **Validation Failed**: Errors found in GitOps configuration\n\n`;
            comment += `Please check the validation output above for details.\n\n`;
          }
          
          comment += `### Configuration Used\n`;
          comment += `- **Fail on Errors**: ✅ Enabled (exit code 1)\n`;
          comment += `- **Fail on Warnings**: ❌ Disabled (exit code 2)\n`;
          comment += `- **Fail on Info**: ❌ Disabled (exit code 3)\n\n`;
          
          comment += `### Legend\n`;
          comment += `- 🟢 **Green**: Valid resources\n`;
          comment += `- 🔴 **Red**: Broken references\n`;
          comment += `- 🟠 **Orange**: Warnings (deprecated APIs)\n`;
          comment += `- 🔴 **Red**: Orphaned resources\n\n`;
          comment += `> 📊 **Generated by** [gitops-validator](https://github.com/moon-hex/gitops-validator)`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
    - name: Upload Artifacts
      if: steps.validation.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: gitops-validation-results
        path: |
          dependency-chart.md
          .gitops-validator.yaml
          
    - name: Fail Job on Validation Errors
      if: steps.validation.outcome == 'failure'
      run: |
        echo "❌ GitOps validation failed with errors. Please fix the issues before merging."
        exit 1