name: Validate GitOps with gitops-validator

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install gitops-validator
      run: go install github.com/moon-hex/gitops-validator@latest

    - name: Run gitops-validator
      run: |
        gitops-validator --path . --verbose
