name: GitOps Validation with Dependency Chart

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-gitops:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install GitOps Validator
      run: |
        go install github.com/moon-hex/gitops-validator@latest
        
    - name: Generate Dependency Chart
      run: |
        # Generate Mermaid chart and save to file
        gitops-validator --path . --chart mermaid --chart-output dependency-chart.md --verbose
        
        # Also generate tree format for comparison
        gitops-validator --path . --chart tree --chart-output dependency-tree.txt --verbose
        
    - name: Validate GitOps Repository
      run: |
        gitops-validator --path . --verbose
        
    - name: Upload Dependency Chart
      uses: actions/upload-artifact@v4
      with:
        name: dependency-charts
        path: |
          dependency-chart.md
          dependency-tree.txt
          
    - name: Comment PR with Dependency Chart
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const chart = fs.readFileSync('dependency-chart.md', 'utf8');
          
          const comment = `## ðŸ” GitOps Dependency Chart
          
          This PR includes the following dependency changes:
          
          \`\`\`mermaid
          ${chart}
          \`\`\`
          
          ### Legend
          - ðŸŸ¢ **Green**: Valid resources
          - ðŸ”´ **Red**: Broken references  
          - ðŸŸ  **Orange**: Warnings (deprecated APIs)
          - ðŸ”´ **Red**: Orphaned resources
          
          > ðŸ“Š **Chart generated by** [gitops-validator](https://github.com/moon-hex/gitops-validator)`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
    - name: Create Dependency Chart Summary
      run: |
        echo "# GitOps Dependency Analysis" > analysis-summary.md
        echo "" >> analysis-summary.md
        echo "## Repository Structure" >> analysis-summary.md
        echo "" >> analysis-summary.md
        echo "The following dependency chart shows the current GitOps repository structure:" >> analysis-summary.md
        echo "" >> analysis-summary.md
        cat dependency-chart.md >> analysis-summary.md
        echo "" >> analysis-summary.md
        echo "## Analysis" >> analysis-summary.md
        echo "" >> analysis-summary.md
        echo "- **Total Resources**: $(gitops-validator --path . --chart json | jq -r '.totalResources')" >> analysis-summary.md
        echo "- **Entry Points**: $(gitops-validator --path . --chart json | jq -r '.entryPoints')" >> analysis-summary.md
        echo "- **Orphaned Resources**: $(gitops-validator --path . --chart json | jq -r '.orphanedResources')" >> analysis-summary.md
        
    - name: Upload Analysis Summary
      uses: actions/upload-artifact@v4
      with:
        name: gitops-analysis
        path: analysis-summary.md