apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: production
spec:
  chart:
    spec:
      chart: frontend
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: my-repo
  interval: 5m