apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  template:
    spec:
      containers:
      - name: test-app
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"

