name: GitOps Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: go mod download
      
    - name: Build validator
      run: go build -o gitops-validator ./main.go
      
    - name: Run validation
      id: validation
      run: |
        echo "Running GitOps validation..."
        ./gitops-validator --path ./ --verbose > validation-results.txt 2>&1
        echo "exit_code=$?" >> $GITHUB_OUTPUT
        
    - name: Display validation results
      if: always()
      run: |
        echo "=== GitOps Validation Results ==="
        cat validation-results.txt
        echo "=== End of Results ==="
        
    - name: Check validation status
      if: steps.validation.outputs.exit_code != 0
      run: |
        echo "❌ GitOps validation failed with exit code ${{ steps.validation.outputs.exit_code }}"
        echo "::error::GitOps validation failed with exit code ${{ steps.validation.outputs.exit_code }}"
        exit ${{ steps.validation.outputs.exit_code }}
        
    - name: Validation passed
      if: steps.validation.outputs.exit_code == 0
      run: |
        echo "✅ GitOps validation passed successfully"
        
    - name: Upload validation results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: |
          validation-results.txt
          gitops-validator
        retention-days: 30
        
    - name: Comment on PR
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const results = fs.readFileSync('validation-results.txt', 'utf8');
          
          const comment = `## 🔍 GitOps Validation Results
          
          <details>
          <summary>Click to view validation output</summary>
          
          \`\`\`
          ${results}
          \`\`\`
          
          </details>
          
          **Status**: ${process.env.VALIDATION_EXIT_CODE === '0' ? '✅ Passed' : '❌ Failed'}
          **Exit Code**: ${process.env.VALIDATION_EXIT_CODE || 'Unknown'}
          
          ---
          *This comment was automatically generated by the GitOps validation workflow.*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
      env:
        VALIDATION_EXIT_CODE: ${{ steps.validation.outputs.exit_code }}